///////////////////////////////////////////////////////////
//  Office.cs
//  Implementation of the Class Office
//  Generated by Enterprise Architect
//  Created on:      12-¡.¾.-2019 18:06:17
//  Original author: pb157094
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Office {

	public Name m_Name;
	public Id m_Id;
	public DataForEvaluation m_DataForEvaluation;
	private Score m_Score;
	public PointOfEvaluation m_PointOfEvaluation;

	public Office(){

	}

	~Office(){

	}

}//end Office